---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elakbou-flux-helm
  namespace: elakbou
spec:
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo
      version: '>4.0.0'
  interval: 1m0s
  releaseName: elakbou-flux-helm
  values:
    logLevel: debug
    replicaCount: 4
    ui:
      color: blue

